name: Pruebas

on: [push, pull_request]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: npm install -g http-server

    - name: Ejecutar servidor web
      run: |
        http-server -p 8080 &
        sleep 3

    - name: Ejecutar prueba unitaria
      run: |
        resultado=$(curl -s http://localhost:8080 | grep -c "¡Hola Mundo desde HTML!")
        if [ "$resultado" -eq "1" ]; then
          echo "La prueba unitaria pasó correctamente!"
        else
          echo "La prueba unitaria falló: El mensaje no coincide!"
          exit 1
        fi
